name: Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up node
        uses: actions/setup-node@v1
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Install test node dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y \
            cmake pkg-config libssl-dev clang

      - name: Install test node
        run: |
          cargo install --git https://github.com/matter-labs/era-test-node.git --locked

      - name: Set output of cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Node dependency cache
        uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            yarn-

      - name: Install dependencies
        run: yarn --frozen-lockfile --network-concurrency 1

      - name: Run test node
        run: |
          era_test_node run &

      - name: Run unit tests
        run: yarn test
